{
 "title": "New dashboardавпвап",
 "description": "павп",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "model",
    "label": "model",
    "query": {
     "query": "label_values(anomaly_node_anomaly_score, model)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(anomaly_node_anomaly_score{model=~\"$model\"}, node)"
    }
   },
   {
    "name": "channel",
    "query": {
     "query": "label_values(anomaly_node_anomaly_score_by_channel{model=~\"$model\", node=~\"$node\"}, channel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Панель 1. Текущий anomaly score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "anomaly_node_anomaly_score{model=~\"$model\", node=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Панель 2. Порог аномальности",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "anomaly_node_anomaly_threshold{model=~\"$model\", node=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Панель 3. Score + threshold на одном графике",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "anomaly_node_anomaly_score{model=~\"$model\", node=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "anomaly_node_anomaly_threshold{model=~\"$model\", node=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Панель 4. Флаг аномалии",
   "type": "state-timeline",
   "description": "0 — норма\n1 — аномалия",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "anomaly_node_anomaly_flag{model=~\"$model\", node=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Панель 5. CPU по узлам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "anomaly_node_cpu_utilization{model=~\"$model\", node=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Панель 6. Voltage +12V",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "anomaly_node_voltage_12v{model=~\"$model\", node=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Панель 7. Score по каналам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "anomaly_node_anomaly_score_by_channel{\r\n  model=~\"$model\",\r\n  node=~\"$node\",\r\n  channel=~\"$channel\"\r\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Панель 8. Replay position",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "anomaly_node_stream_position{model=~\"$model\", node=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Панель 9. Window ready",
   "type": "stat",
   "description": "Показывает, заполнено ли окно инференса.\n0 — окно ещё не заполнено\n1 — окно готово",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anomaly_node_window_ready{model=~\"$model\", node=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Панель 10. Активность replay-сервисов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anomaly_replay_active{model=~\"$model\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}